/**
 * HypeVox — Translations
 * MIT License — github.com/sahinguclu/HypeVox
 */

const LANG = {
  en: {
    name: 'English',
    title: 'HypeVox',
    mute: 'Mute',
    maxVol: '1000%',
    default: '● Default',
    muted: '● Muted',
    soundProfile: 'Sound Profile',
    off: 'Off',
    flat: 'Flat',
    bass: 'Bass Boost',
    voice: 'Voice Enhance',
    treble: 'Treble Boost',
    loud: 'Loudness',
    podcast: 'Podcast',
    rock: 'Rock',
    pop: 'Pop',
    jazz: 'Jazz',
    hiphop: 'Hip-Hop',
    classical: 'Classical',
    electronic: 'Electronic',
    reset: '↺ Reset 100%',
    restore: 'Restore',
    tabsPlaying: '🔊 Tabs playing audio',
    noAudio: 'No audio playing',
    madeBy: 'Made by',
    withLove: 'with',
    sourceCode: 'Source Code',
  },
  tr: {
    name: 'Turkish — Türkçe',
    title: 'HypeVox',
    mute: 'Sessiz',
    maxVol: '%1000',
    default: '● Varsayılan',
    muted: '● Sessiz',
    soundProfile: 'Ses Profili',
    off: 'Kapalı',
    flat: 'Düz',
    bass: 'Bas Güçlendirme',
    voice: 'Ses Netliği',
    treble: 'Tiz Güçlendirme',
    loud: 'Ses Yüksekliği',
    podcast: 'Podcast',
    rock: 'Rock',
    pop: 'Pop',
    jazz: 'Caz',
    hiphop: 'Hip-Hop',
    classical: 'Klasik',
    electronic: 'Elektronik',
    reset: '↺ %100 Sıfırla',
    restore: 'Geri Yükle',
    tabsPlaying: '🔊 Ses çalan sekmeler',
    noAudio: 'Ses çalan sekme yok',
    madeBy: 'Yapan',
    withLove: 'ile',
    sourceCode: 'Kaynak Kodu',
  },
  de: {
    name: 'German — Deutsch',
    title: 'HypeVox',
    mute: 'Stumm',
    maxVol: '1000%',
    default: '● Standard',
    muted: '● Stumm',
    soundProfile: 'Klangprofil',
    off: 'Aus',
    flat: 'Neutral',
    bass: 'Bass Boost',
    voice: 'Stimme',
    treble: 'Höhen Boost',
    loud: 'Lautstärke',
    podcast: 'Podcast',
    rock: 'Rock',
    pop: 'Pop',
    jazz: 'Jazz',
    hiphop: 'Hip-Hop',
    classical: 'Klassik',
    electronic: 'Elektronisch',
    reset: '↺ 100% Reset',
    restore: 'Wiederherstellen',
    tabsPlaying: '🔊 Tabs mit Audio',
    noAudio: 'Kein Audio',
    madeBy: 'Von',
    withLove: 'mit',
    sourceCode: 'Quellcode',
  },
  fr: {
    name: 'French — Français',
    title: 'HypeVox',
    mute: 'Muet',
    maxVol: '1000%',
    default: '● Défaut',
    muted: '● Muet',
    soundProfile: 'Profil Sonore',
    off: 'Désactivé',
    flat: 'Neutre',
    bass: 'Amplification Basses',
    voice: 'Clarté Vocale',
    treble: 'Amplification Aigus',
    loud: 'Sonorité',
    podcast: 'Podcast',
    rock: 'Rock',
    pop: 'Pop',
    jazz: 'Jazz',
    hiphop: 'Hip-Hop',
    classical: 'Classique',
    electronic: 'Électronique',
    reset: '↺ Réinitialiser 100%',
    restore: 'Restaurer',
    tabsPlaying: '🔊 Onglets avec audio',
    noAudio: 'Aucun audio',
    madeBy: 'Fait par',
    withLove: 'avec',
    sourceCode: 'Code Source',
  },
  es: {
    name: 'Spanish — Español',
    title: 'HypeVox',
    mute: 'Silencio',
    maxVol: '1000%',
    default: '● Defecto',
    muted: '● Silencio',
    soundProfile: 'Perfil de Sonido',
    off: 'Apagado',
    flat: 'Plano',
    bass: 'Refuerzo Graves',
    voice: 'Claridad Vocal',
    treble: 'Refuerzo Agudos',
    loud: 'Volumen',
    podcast: 'Podcast',
    rock: 'Rock',
    pop: 'Pop',
    jazz: 'Jazz',
    hiphop: 'Hip-Hop',
    classical: 'Clásica',
    electronic: 'Electrónica',
    reset: '↺ Restablecer 100%',
    restore: 'Restaurar',
    tabsPlaying: '🔊 Pestañas con audio',
    noAudio: 'Sin audio',
    madeBy: 'Hecho por',
    withLove: 'con',
    sourceCode: 'Código Fuente',
  },
  ru: {
    name: 'Russian — Русский',
    title: 'HypeVox',
    mute: 'Без звука',
    maxVol: '1000%',
    default: '● Стандарт',
    muted: '● Без звука',
    soundProfile: 'Звуковой Профиль',
    off: 'Выкл',
    flat: 'Ровный',
    bass: 'Усиление Басов',
    voice: 'Четкость Голоса',
    treble: 'Усиление Высоких',
    loud: 'Громкость',
    podcast: 'Подкаст',
    rock: 'Рок',
    pop: 'Поп',
    jazz: 'Джаз',
    hiphop: 'Хип-Хоп',
    classical: 'Классика',
    electronic: 'Электроника',
    reset: '↺ Сброс 100%',
    restore: 'Восстановить',
    tabsPlaying: '🔊 Вкладки с аудио',
    noAudio: 'Нет аудио',
    madeBy: 'Создатель',
    withLove: 'с',
    sourceCode: 'Исходный Код',
  },
  ja: {
    name: 'Japanese — 日本語',
    title: 'HypeVox',
    mute: 'ミュート',
    maxVol: '1000%',
    default: '● デフォルト',
    muted: '● ミュート',
    soundProfile: 'サウンドプロファイル',
    off: 'オフ',
    flat: 'フラット',
    bass: '低音ブースト',
    voice: '音声明瞭化',
    treble: '高音ブースト',
    loud: 'ラウドネス',
    podcast: 'ポッドキャスト',
    rock: 'ロック',
    pop: 'ポップ',
    jazz: 'ジャズ',
    hiphop: 'ヒップホップ',
    classical: 'クラシック',
    electronic: 'エレクトロニック',
    reset: '↺ 100%にリセット',
    restore: '復元',
    tabsPlaying: '🔊 音声再生中のタブ',
    noAudio: '音声なし',
    madeBy: '作者',
    withLove: 'から',
    sourceCode: 'ソースコード',
  },
  zh_CN: {
    name: 'Chinese (Simplified) — 简体中文',
    title: 'HypeVox',
    mute: '静音',
    maxVol: '1000%',
    default: '● 默认',
    muted: '● 静音',
    soundProfile: '声音配置',
    off: '关闭',
    flat: '平坦',
    bass: '低音增强',
    voice: '语音清晰',
    treble: '高音增强',
    loud: '响度',
    podcast: '播客',
    rock: '摇滚',
    pop: '流行',
    jazz: '爵士',
    hiphop: '嘻哈',
    classical: '古典',
    electronic: '电子',
    reset: '↺ 重置 100%',
    restore: '恢复',
    tabsPlaying: '🔊 正在播放音频的标签',
    noAudio: '无音频',
    madeBy: '作者',
    withLove: '用',
    sourceCode: '源代码',
  },
  ko: {
    name: 'Korean — 한국어',
    title: 'HypeVox',
    mute: '음소거',
    maxVol: '1000%',
    default: '● 기본값',
    muted: '● 음소거',
    soundProfile: '사운드 프로필',
    off: '끄기',
    flat: '플랫',
    bass: '저음 부스트',
    voice: '음성 선명도',
    treble: '고음 부스트',
    loud: '라우드니스',
    podcast: '팟캐스트',
    rock: '록',
    pop: '팝',
    jazz: '재즈',
    hiphop: '힙합',
    classical: '클래식',
    electronic: '일렉트로닉',
    reset: '↺ 100% 초기화',
    restore: '복원',
    tabsPlaying: '🔊 오디오 재생 중인 탭',
    noAudio: '오디오 없음',
    madeBy: '제작',
    withLove: '으로',
    sourceCode: '소스 코드',
  },
  it: {
    name: 'Italian — Italiano',
    title: 'HypeVox',
    mute: 'Muto',
    maxVol: '1000%',
    default: '● Predefinito',
    muted: '● Muto',
    soundProfile: 'Profilo Audio',
    off: 'Spento',
    flat: 'Piatto',
    bass: 'Potenziamento Bassi',
    voice: 'Chiarezza Vocale',
    treble: 'Potenziamento Alti',
    loud: 'Volume',
    podcast: 'Podcast',
    rock: 'Rock',
    pop: 'Pop',
    jazz: 'Jazz',
    hiphop: 'Hip-Hop',
    classical: 'Classica',
    electronic: 'Elettronica',
    reset: '↺ Ripristina 100%',
    restore: 'Ripristina',
    tabsPlaying: '🔊 Schede con audio',
    noAudio: 'Nessun audio',
    madeBy: 'Fatto da',
    withLove: 'con',
    sourceCode: 'Codice Sorgente',
  },
  pt: {
    name: 'Portuguese — Português',
    title: 'HypeVox',
    mute: 'Mudo',
    maxVol: '1000%',
    default: '● Padrão',
    muted: '● Mudo',
    soundProfile: 'Perfil de Som',
    off: 'Desligado',
    flat: 'Plano',
    bass: 'Reforço de Graves',
    voice: 'Clareza Vocal',
    treble: 'Reforço de Agudos',
    loud: 'Sonoridade',
    podcast: 'Podcast',
    rock: 'Rock',
    pop: 'Pop',
    jazz: 'Jazz',
    hiphop: 'Hip-Hop',
    classical: 'Clássica',
    electronic: 'Eletrônica',
    reset: '↺ Redefinir 100%',
    restore: 'Restaurar',
    tabsPlaying: '🔊 Abas com áudio',
    noAudio: 'Sem áudio',
    madeBy: 'Feito por',
    withLove: 'com',
    sourceCode: 'Código Fonte',
  },
  ar: {
    name: 'Arabic — العربية',
    title: 'HypeVox',
    mute: 'كتم',
    maxVol: '1000%',
    default: '● افتراضي',
    muted: '● مكتوم',
    soundProfile: 'ملف الصوت',
    off: 'إيقاف',
    flat: 'مسطح',
    bass: 'تعزيز الجهير',
    voice: 'وضوح الصوت',
    treble: 'تعزيز الحاد',
    loud: 'جهارة',
    podcast: 'بودكاست',
    rock: 'روك',
    pop: 'بوب',
    jazz: 'جاز',
    hiphop: 'هيب هوب',
    classical: 'كلاسيكي',
    electronic: 'إلكتروني',
    reset: '↺ إعادة 100%',
    restore: 'استعادة',
    tabsPlaying: '🔊 علامات تبويب بصوت',
    noAudio: 'لا يوجد صوت',
    madeBy: 'صنع بواسطة',
    withLove: 'مع',
    sourceCode: 'الكود المصدري',
  },
  hi: {
    name: 'Hindi — हिन्दी',
    title: 'HypeVox',
    mute: 'मौन',
    maxVol: '1000%',
    default: '● डिफ़ॉल्ट',
    muted: '● मौन',
    soundProfile: 'ध्वनि प्रोफ़ाइल',
    off: 'बंद',
    flat: 'सपाट',
    bass: 'बास बूस्ट',
    voice: 'आवाज़ स्पष्टता',
    treble: 'ट्रेबल बूस्ट',
    loud: 'प्रबलता',
    podcast: 'पॉडकास्ट',
    rock: 'रॉक',
    pop: 'पॉप',
    jazz: 'जैज़',
    hiphop: 'हिप-हॉप',
    classical: 'शास्त्रीय',
    electronic: 'इलेक्ट्रॉनिक',
    reset: '↺ 100% रीसेट',
    restore: 'पुनर्स्थापित',
    tabsPlaying: '🔊 ऑडियो वाले टैब',
    noAudio: 'कोई ऑडियो नहीं',
    madeBy: 'द्वारा बनाया गया',
    withLove: 'के साथ',
    sourceCode: 'सोर्स कोड',
  },
  si: {
    name: 'Sinhala — සිංහල',
    title: 'HypeVox',
    mute: 'නිහඬ',
    maxVol: '1000%',
    default: '● පෙරනිමි',
    muted: '● නිහඬ',
    soundProfile: 'ශබ්ද පැතිකඩ',
    off: 'අක්‍රිය',
    flat: 'සමතල',
    bass: 'බාස් වර්ධක',
    voice: 'හඬ පැහැදිලිතාව',
    treble: 'ට්‍රෙබල් වර්ධක',
    loud: 'ඝෝෂාකාරී',
    podcast: 'පොඩ්කාස්ට්',
    rock: 'රොක්',
    pop: 'පොප්',
    jazz: 'ජෑස්',
    hiphop: 'හිප්-හොප්',
    classical: 'සම්භාව්‍ය',
    electronic: 'ඉලෙක්ට්‍රොනික',
    reset: '↺ 100% යළි සකසන්න',
    restore: 'ප්‍රතිසාධනය',
    tabsPlaying: '🔊 ශ්‍රව්‍ය වාදනය වන ටැබ්',
    noAudio: 'ශ්‍රව්‍ය නැත',
    madeBy: 'විසින් නිර්මාණය',
    withLove: 'සමඟ',
    sourceCode: 'මූලාශ්‍ර කේතය',
  },
  nl: { name:'Dutch — Nederlands', title:'HypeVox', mute:'Dempen', maxVol:'1000%', default:'● Standaard', muted:'● Gedempt', soundProfile:'Geluidsprofiel', off:'Uit', flat:'Vlak', bass:'Bas Boost', voice:'Stemhelderheid', treble:'Treble Boost', loud:'Luidheid', podcast:'Podcast', rock:'Rock', pop:'Pop', jazz:'Jazz', hiphop:'Hip-Hop', classical:'Klassiek', electronic:'Elektronisch', reset:'↺ 100% Reset', restore:'Herstellen', tabsPlaying:'🔊 Tabs met audio', noAudio:'Geen audio', madeBy:'Gemaakt door', withLove:'met', sourceCode:'Broncode' },
  pl: { name:'Polish — Polski', title:'HypeVox', mute:'Wycisz', maxVol:'1000%', default:'● Domyślnie', muted:'● Wyciszony', soundProfile:'Profil Dźwięku', off:'Wył', flat:'Płaski', bass:'Wzmocnienie Basów', voice:'Wyrazistość Głosu', treble:'Wzmocnienie Tonów', loud:'Głośność', podcast:'Podcast', rock:'Rock', pop:'Pop', jazz:'Jazz', hiphop:'Hip-Hop', classical:'Klasyczna', electronic:'Elektroniczna', reset:'↺ Reset 100%', restore:'Przywróć', tabsPlaying:'🔊 Karty z dźwiękiem', noAudio:'Brak dźwięku', madeBy:'Wykonane przez', withLove:'z', sourceCode:'Kod Źródłowy' },
  vi: { name:'Vietnamese — Tiếng Việt', title:'HypeVox', mute:'Tắt tiếng', maxVol:'1000%', default:'● Mặc định', muted:'● Tắt tiếng', soundProfile:'Cấu Hình Âm Thanh', off:'Tắt', flat:'Phẳng', bass:'Tăng Âm Trầm', voice:'Rõ Giọng Nói', treble:'Tăng Âm Cao', loud:'Độ Lớn', podcast:'Podcast', rock:'Rock', pop:'Pop', jazz:'Jazz', hiphop:'Hip-Hop', classical:'Cổ Điển', electronic:'Điện Tử', reset:'↺ Đặt Lại 100%', restore:'Khôi Phục', tabsPlaying:'🔊 Tab đang phát âm thanh', noAudio:'Không có âm thanh', madeBy:'Tạo bởi', withLove:'với', sourceCode:'Mã Nguồn' },
  th: { name:'Thai — ไทย', title:'HypeVox', mute:'ปิดเสียง', maxVol:'1000%', default:'● ค่าเริ่มต้น', muted:'● ปิดเสียง', soundProfile:'โปรไฟล์เสียง', off:'ปิด', flat:'เรียบ', bass:'เพิ่มเบส', voice:'เสียงพูดชัด', treble:'เพิ่มแหลม', loud:'ความดัง', podcast:'พอดแคสต์', rock:'ร็อค', pop:'ป๊อป', jazz:'แจ๊ส', hiphop:'ฮิปฮอป', classical:'คลาสสิค', electronic:'อิเล็กทรอนิกส์', reset:'↺ รีเซ็ต 100%', restore:'คืนค่า', tabsPlaying:'🔊 แท็บที่เล่นเสียง', noAudio:'ไม่มีเสียง', madeBy:'สร้างโดย', withLove:'ด้วย', sourceCode:'ซอร์สโค้ด' },
  id: { name:'Indonesian — Bahasa Indonesia', title:'HypeVox', mute:'Bisukan', maxVol:'1000%', default:'● Bawaan', muted:'● Dibisukan', soundProfile:'Profil Suara', off:'Mati', flat:'Datar', bass:'Penambah Bass', voice:'Kejernihan Suara', treble:'Penambah Treble', loud:'Kenyaringan', podcast:'Podcast', rock:'Rock', pop:'Pop', jazz:'Jazz', hiphop:'Hip-Hop', classical:'Klasik', electronic:'Elektronik', reset:'↺ Atur Ulang 100%', restore:'Pulihkan', tabsPlaying:'🔊 Tab dengan audio', noAudio:'Tidak ada audio', madeBy:'Dibuat oleh', withLove:'dengan', sourceCode:'Kode Sumber' },
  sv: { name:'Swedish — Svenska', title:'HypeVox', mute:'Tyst', maxVol:'1000%', default:'● Standard', muted:'● Tyst', soundProfile:'Ljudprofil', off:'Av', flat:'Platt', bass:'Basförstärkning', voice:'Rösttydlighet', treble:'Diskantförstärkning', loud:'Ljudstyrka', podcast:'Podcast', rock:'Rock', pop:'Pop', jazz:'Jazz', hiphop:'Hip-Hop', classical:'Klassiskt', electronic:'Elektroniskt', reset:'↺ Återställ 100%', restore:'Återställ', tabsPlaying:'🔊 Flikar med ljud', noAudio:'Inget ljud', madeBy:'Gjord av', withLove:'med', sourceCode:'Källkod' },
  cs: { name:'Czech — Čeština', title:'HypeVox', mute:'Ztlumit', maxVol:'1000%', default:'● Výchozí', muted:'● Ztlumeno', soundProfile:'Zvukový Profil', off:'Vypnuto', flat:'Plochý', bass:'Zesílení Basů', voice:'Čistota Hlasu', treble:'Zesílení Výšek', loud:'Hlasitost', podcast:'Podcast', rock:'Rock', pop:'Pop', jazz:'Jazz', hiphop:'Hip-Hop', classical:'Klasika', electronic:'Elektronika', reset:'↺ Reset 100%', restore:'Obnovit', tabsPlaying:'🔊 Karty se zvukem', noAudio:'Žádný zvuk', madeBy:'Vytvořil', withLove:'s', sourceCode:'Zdrojový Kód' },
  ro: { name:'Romanian — Română', title:'HypeVox', mute:'Mut', maxVol:'1000%', default:'● Implicit', muted:'● Mut', soundProfile:'Profil Sunet', off:'Oprit', flat:'Plat', bass:'Amplificare Bas', voice:'Claritate Vocală', treble:'Amplificare Înalte', loud:'Sonoritate', podcast:'Podcast', rock:'Rock', pop:'Pop', jazz:'Jazz', hiphop:'Hip-Hop', classical:'Clasică', electronic:'Electronică', reset:'↺ Resetare 100%', restore:'Restaurare', tabsPlaying:'🔊 File cu audio', noAudio:'Fără audio', madeBy:'Creat de', withLove:'cu', sourceCode:'Cod Sursă' },
  hu: { name:'Hungarian — Magyar', title:'HypeVox', mute:'Némítás', maxVol:'1000%', default:'● Alapértelmezett', muted:'● Némítva', soundProfile:'Hangprofil', off:'Ki', flat:'Semleges', bass:'Basszus Erősítés', voice:'Beszéd Tisztaság', treble:'Magas Erősítés', loud:'Hangerősség', podcast:'Podcast', rock:'Rock', pop:'Pop', jazz:'Jazz', hiphop:'Hip-Hop', classical:'Klasszikus', electronic:'Elektronikus', reset:'↺ 100% Visszaállítás', restore:'Visszaállítás', tabsPlaying:'🔊 Hangot lejátszó lapok', noAudio:'Nincs hang', madeBy:'Készítette', withLove:'-val', sourceCode:'Forráskód' },
  uk: { name:'Ukrainian — Українська', title:'HypeVox', mute:'Без звуку', maxVol:'1000%', default:'● Стандарт', muted:'● Без звуку', soundProfile:'Звуковий Профіль', off:'Вимк', flat:'Рівний', bass:'Підсилення Басів', voice:'Чіткість Голосу', treble:'Підсилення Високих', loud:'Гучність', podcast:'Подкаст', rock:'Рок', pop:'Поп', jazz:'Джаз', hiphop:'Хіп-Хоп', classical:'Класика', electronic:'Електроніка', reset:'↺ Скинути 100%', restore:'Відновити', tabsPlaying:'🔊 Вкладки з аудіо', noAudio:'Немає аудіо', madeBy:'Створив', withLove:'з', sourceCode:'Вихідний Код' },
  fil: { name:'Filipino', title:'HypeVox', mute:'I-mute', maxVol:'1000%', default:'● Default', muted:'● Naka-mute', soundProfile:'Profile ng Tunog', off:'Naka-off', flat:'Patag', bass:'Lakas ng Bass', voice:'Linaw ng Boses', treble:'Lakas ng Treble', loud:'Lakas', podcast:'Podcast', rock:'Rock', pop:'Pop', jazz:'Jazz', hiphop:'Hip-Hop', classical:'Klasikal', electronic:'Elektroniko', reset:'↺ I-reset 100%', restore:'Ibalik', tabsPlaying:'🔊 Mga tab na may audio', noAudio:'Walang audio', madeBy:'Gawa ni', withLove:'nang may', sourceCode:'Source Code' },
  ms: { name:'Malay — Bahasa Melayu', title:'HypeVox', mute:'Senyap', maxVol:'1000%', default:'● Lalai', muted:'● Senyap', soundProfile:'Profil Bunyi', off:'Mati', flat:'Rata', bass:'Penggalak Bass', voice:'Kejelasan Suara', treble:'Penggalak Treble', loud:'Kenyaringan', podcast:'Podcast', rock:'Rock', pop:'Pop', jazz:'Jazz', hiphop:'Hip-Hop', classical:'Klasik', electronic:'Elektronik', reset:'↺ Tetapkan 100%', restore:'Pulihkan', tabsPlaying:'🔊 Tab dengan audio', noAudio:'Tiada audio', madeBy:'Dibuat oleh', withLove:'dengan', sourceCode:'Kod Sumber' },
  no: { name:'Norwegian — Norsk', title:'HypeVox', mute:'Demp', maxVol:'1000%', default:'● Standard', muted:'● Dempet', soundProfile:'Lydprofil', off:'Av', flat:'Flat', bass:'Bass Boost', voice:'Stemmeklarhet', treble:'Treble Boost', loud:'Lydstyrke', podcast:'Podcast', rock:'Rock', pop:'Pop', jazz:'Jazz', hiphop:'Hip-Hop', classical:'Klassisk', electronic:'Elektronisk', reset:'↺ Tilbakestill 100%', restore:'Gjenopprett', tabsPlaying:'🔊 Faner med lyd', noAudio:'Ingen lyd', madeBy:'Laget av', withLove:'med', sourceCode:'Kildekode' },
  da: { name:'Danish — Dansk', title:'HypeVox', mute:'Lydløs', maxVol:'1000%', default:'● Standard', muted:'● Lydløs', soundProfile:'Lydprofil', off:'Fra', flat:'Flad', bass:'Bas Boost', voice:'Stemmeklarhed', treble:'Diskant Boost', loud:'Lydstyrke', podcast:'Podcast', rock:'Rock', pop:'Pop', jazz:'Jazz', hiphop:'Hip-Hop', classical:'Klassisk', electronic:'Elektronisk', reset:'↺ Nulstil 100%', restore:'Gendan', tabsPlaying:'🔊 Faner med lyd', noAudio:'Ingen lyd', madeBy:'Lavet af', withLove:'med', sourceCode:'Kildekode' },
  fi: { name:'Finnish — Suomi', title:'HypeVox', mute:'Mykistä', maxVol:'1000%', default:'● Oletus', muted:'● Mykistetty', soundProfile:'Ääniprofiili', off:'Pois', flat:'Tasainen', bass:'Basson Vahvistus', voice:'Puheen Selkeys', treble:'Diskantin Vahvistus', loud:'Äänekkyys', podcast:'Podcast', rock:'Rock', pop:'Pop', jazz:'Jazz', hiphop:'Hip-Hop', classical:'Klassinen', electronic:'Elektroninen', reset:'↺ Palauta 100%', restore:'Palauta', tabsPlaying:'🔊 Välilehdet joissa ääni', noAudio:'Ei ääntä', madeBy:'Tekijä', withLove:'ja', sourceCode:'Lähdekoodi' },
  el: { name:'Greek — Ελληνικά', title:'HypeVox', mute:'Σίγαση', maxVol:'1000%', default:'● Προεπιλογή', muted:'● Σίγαση', soundProfile:'Προφίλ Ήχου', off:'Ανενεργό', flat:'Επίπεδο', bass:'Ενίσχυση Μπάσων', voice:'Ευκρίνεια Φωνής', treble:'Ενίσχυση Πρίμων', loud:'Ένταση', podcast:'Podcast', rock:'Ροκ', pop:'Ποπ', jazz:'Τζαζ', hiphop:'Χιπ-Χοπ', classical:'Κλασική', electronic:'Ηλεκτρονική', reset:'↺ Επαναφορά 100%', restore:'Επαναφορά', tabsPlaying:'🔊 Καρτέλες με ήχο', noAudio:'Χωρίς ήχο', madeBy:'Δημιουργήθηκε από', withLove:'με', sourceCode:'Πηγαίος Κώδικας' },
  he: { name:'Hebrew — עברית', title:'HypeVox', mute:'השתק', maxVol:'1000%', default:'● ברירת מחדל', muted:'● מושתק', soundProfile:'פרופיל צליל', off:'כבוי', flat:'שטוח', bass:'הגברת בס', voice:'בהירות קול', treble:'הגברת טרבל', loud:'עוצמה', podcast:'פודקאסט', rock:'רוק', pop:'פופ', jazz:"ג'אז", hiphop:'היפ-הופ', classical:'קלאסי', electronic:'אלקטרוני', reset:'↺ איפוס 100%', restore:'שחזור', tabsPlaying:'🔊 כרטיסיות עם שמע', noAudio:'אין שמע', madeBy:'נוצר על ידי', withLove:'עם', sourceCode:'קוד מקור' },
  bn: { name:'Bengali — বাংলা', title:'HypeVox', mute:'নীরব', maxVol:'1000%', default:'● ডিফল্ট', muted:'● নীরব', soundProfile:'সাউন্ড প্রোফাইল', off:'বন্ধ', flat:'সমতল', bass:'বেস বুস্ট', voice:'কণ্ঠস্বর স্পষ্টতা', treble:'ট্রেবল বুস্ট', loud:'উচ্চতা', podcast:'পডকাস্ট', rock:'রক', pop:'পপ', jazz:'জ্যাজ', hiphop:'হিপ-হপ', classical:'ক্লাসিক্যাল', electronic:'ইলেকট্রনিক', reset:'↺ 100% রিসেট', restore:'পুনরুদ্ধার', tabsPlaying:'🔊 অডিও সহ ট্যাব', noAudio:'কোনো অডিও নেই', madeBy:'তৈরি করেছেন', withLove:'এর সাথে', sourceCode:'সোর্স কোড' },
  ur: { name:'Urdu — اردو', title:'HypeVox', mute:'خاموش', maxVol:'1000%', default:'● ڈیفالٹ', muted:'● خاموش', soundProfile:'صوتی پروفائل', off:'بند', flat:'فلیٹ', bass:'باس بوسٹ', voice:'آواز کی وضاحت', treble:'ٹریبل بوسٹ', loud:'بلندی', podcast:'پوڈکاسٹ', rock:'راک', pop:'پاپ', jazz:'جاز', hiphop:'ہپ ہاپ', classical:'کلاسیکل', electronic:'الیکٹرانک', reset:'↺ 100% ری سیٹ', restore:'بحال', tabsPlaying:'🔊 آڈیو والے ٹیبز', noAudio:'کوئی آڈیو نہیں', madeBy:'بنایا گیا', withLove:'کے ساتھ', sourceCode:'سورس کوڈ' },
  ta: { name:'Tamil — தமிழ்', title:'HypeVox', mute:'ஒலியடக்கு', maxVol:'1000%', default:'● இயல்புநிலை', muted:'● ஒலியடக்கப்பட்டது', soundProfile:'ஒலி விவரம்', off:'முடக்கு', flat:'சமதள', bass:'பாஸ் பூஸ்ட்', voice:'குரல் தெளிவு', treble:'ட்ரெபிள் பூஸ்ட்', loud:'ஒலியளவு', podcast:'பாட்காஸ்ட்', rock:'ராக்', pop:'பாப்', jazz:'ஜாஸ்', hiphop:'ஹிப்-ஹாப்', classical:'கிளாசிக்கல்', electronic:'எலக்ட்ரானிக்', reset:'↺ 100% மீட்டமை', restore:'மீட்டெடு', tabsPlaying:'🔊 ஆடியோவுடன் தாவல்கள்', noAudio:'ஆடியோ இல்லை', madeBy:'உருவாக்கியவர்', withLove:'உடன்', sourceCode:'மூல குறியீடு' },
  am: { name:'Amharic — አማርኛ', title:'HypeVox', mute:'ድምጸ-ከል', maxVol:'1000%', default:'● ነባሪ', muted:'● ድምጸ-ከል', soundProfile:'የድምጽ መገለጫ', off:'ጠፍቷል', flat:'ጠፍጣፋ', bass:'ባስ ማጉላት', voice:'የድምጽ ግልጽነት', treble:'ትሬብል ማጉላት', loud:'ጮክታ', podcast:'ፖድካስት', rock:'ሮክ', pop:'ፖፕ', jazz:'ጃዝ', hiphop:'ሂፕ-ሆፕ', classical:'ክላሲካል', electronic:'ኤሌክትሮኒክ', reset:'↺ 100% ዳግም አስጀምር', restore:'መልሶ አቋቁም', tabsPlaying:'🔊 ድምጽ ያላቸው ትሮች', noAudio:'ምንም ድምጽ የለም', madeBy:'የተሰራው በ', withLove:'በ', sourceCode:'ምንጭ ኮድ' },
  bg: { name:'Bulgarian — Български', title:'HypeVox', mute:'Без звук', maxVol:'1000%', default:'● Стандартно', muted:'● Без звук', soundProfile:'Звуков Профил', off:'Изкл', flat:'Плосък', bass:'Усилване на Баси', voice:'Яснота на Гласа', treble:'Усилване на Високи', loud:'Сила на Звука', podcast:'Подкаст', rock:'Рок', pop:'Поп', jazz:'Джаз', hiphop:'Хип-Хоп', classical:'Класическа', electronic:'Електронна', reset:'↺ Нулиране 100%', restore:'Възстановяване', tabsPlaying:'🔊 Раздели с аудио', noAudio:'Няма аудио', madeBy:'Направено от', withLove:'с', sourceCode:'Изходен Код' },
  ca: { name:'Catalan — Català', title:'HypeVox', mute:'Silenci', maxVol:'1000%', default:'● Per defecte', muted:'● Silenci', soundProfile:'Perfil de So', off:'Apagat', flat:'Pla', bass:'Reforç de Greus', voice:'Claredat Vocal', treble:'Reforç d\'Aguts', loud:'Sonoritat', podcast:'Podcast', rock:'Rock', pop:'Pop', jazz:'Jazz', hiphop:'Hip-Hop', classical:'Clàssica', electronic:'Electrònica', reset:'↺ Restablir 100%', restore:'Restaurar', tabsPlaying:'🔊 Pestanyes amb àudio', noAudio:'Sense àudio', madeBy:'Fet per', withLove:'amb', sourceCode:'Codi Font' },
  en_GB: { name:'English (UK)', title:'HypeVox', mute:'Mute', maxVol:'1000%', default:'● Default', muted:'● Muted', soundProfile:'Sound Profile', off:'Off', flat:'Flat', bass:'Bass Boost', voice:'Voice Enhance', treble:'Treble Boost', loud:'Loudness', podcast:'Podcast', rock:'Rock', pop:'Pop', jazz:'Jazz', hiphop:'Hip-Hop', classical:'Classical', electronic:'Electronic', reset:'↺ Reset 100%', restore:'Restore', tabsPlaying:'🔊 Tabs playing audio', noAudio:'No audio playing', madeBy:'Made by', withLove:'with', sourceCode:'Source Code' },
  en_US: { name:'English (US)', title:'HypeVox', mute:'Mute', maxVol:'1000%', default:'● Default', muted:'● Muted', soundProfile:'Sound Profile', off:'Off', flat:'Flat', bass:'Bass Boost', voice:'Voice Enhance', treble:'Treble Boost', loud:'Loudness', podcast:'Podcast', rock:'Rock', pop:'Pop', jazz:'Jazz', hiphop:'Hip-Hop', classical:'Classical', electronic:'Electronic', reset:'↺ Reset 100%', restore:'Restore', tabsPlaying:'🔊 Tabs playing audio', noAudio:'No audio playing', madeBy:'Made by', withLove:'with', sourceCode:'Source Code' },
  es_419: { name:'Spanish (Latin America) — Español', title:'HypeVox', mute:'Silencio', maxVol:'1000%', default:'● Defecto', muted:'● Silencio', soundProfile:'Perfil de Sonido', off:'Apagado', flat:'Plano', bass:'Refuerzo Graves', voice:'Claridad Vocal', treble:'Refuerzo Agudos', loud:'Volumen', podcast:'Podcast', rock:'Rock', pop:'Pop', jazz:'Jazz', hiphop:'Hip-Hop', classical:'Clásica', electronic:'Electrónica', reset:'↺ Restablecer 100%', restore:'Restaurar', tabsPlaying:'🔊 Pestañas con audio', noAudio:'Sin audio', madeBy:'Hecho por', withLove:'con', sourceCode:'Código Fuente' },
  et: { name:'Estonian — Eesti', title:'HypeVox', mute:'Vaigista', maxVol:'1000%', default:'● Vaikimisi', muted:'● Vaigistatud', soundProfile:'Heliprofiil', off:'Väljas', flat:'Tasane', bass:'Bassi Võimendus', voice:'Hääle Selgus', treble:'Kõrgete Võimendus', loud:'Helitugevus', podcast:'Podcast', rock:'Rock', pop:'Pop', jazz:'Jazz', hiphop:'Hip-Hop', classical:'Klassikaline', electronic:'Elektrooniline', reset:'↺ Lähtesta 100%', restore:'Taasta', tabsPlaying:'🔊 Heliga kaardid', noAudio:'Heli puudub', madeBy:'Teinud', withLove:'-ga', sourceCode:'Lähtekood' },
  fa: { name:'Persian — فارسی', title:'HypeVox', mute:'بی‌صدا', maxVol:'1000%', default:'● پیش‌فرض', muted:'● بی‌صدا', soundProfile:'نمایه صدا', off:'خاموش', flat:'تخت', bass:'تقویت بیس', voice:'وضوح صدا', treble:'تقویت تریبل', loud:'بلندی', podcast:'پادکست', rock:'راک', pop:'پاپ', jazz:'جاز', hiphop:'هیپ‌هاپ', classical:'کلاسیک', electronic:'الکترونیک', reset:'↺ بازنشانی 100%', restore:'بازیابی', tabsPlaying:'🔊 زبانه‌های دارای صدا', noAudio:'بدون صدا', madeBy:'ساخته شده توسط', withLove:'با', sourceCode:'کد منبع' },
  gu: { name:'Gujarati — ગુજરાતી', title:'HypeVox', mute:'મૌન', maxVol:'1000%', default:'● મૂળભૂત', muted:'● મૌન', soundProfile:'ધ્વનિ પ્રોફાઇલ', off:'બંધ', flat:'સપાટ', bass:'બાસ બૂસ્ટ', voice:'અવાજ સ્પષ્ટતા', treble:'ટ્રેબલ બૂસ્ટ', loud:'મોટેપણું', podcast:'પોડકાસ્ટ', rock:'રોક', pop:'પોપ', jazz:'જાઝ', hiphop:'હિપ-હોપ', classical:'શાસ્ત્રીય', electronic:'ઇલેક્ટ્રોનિક', reset:'↺ 100% રીસેટ', restore:'પુનઃસ્થાપિત', tabsPlaying:'🔊 ઑડિઓ સાથે ટેબ્સ', noAudio:'કોઈ ઑડિઓ નથી', madeBy:'દ્વારા બનાવેલ', withLove:'સાથે', sourceCode:'સોર્સ કોડ' },
  hr: { name:'Croatian — Hrvatski', title:'HypeVox', mute:'Utišaj', maxVol:'1000%', default:'● Zadano', muted:'● Utišano', soundProfile:'Zvučni Profil', off:'Isključeno', flat:'Ravno', bass:'Pojačanje Basova', voice:'Jasnoća Glasa', treble:'Pojačanje Visokih', loud:'Glasnoća', podcast:'Podcast', rock:'Rock', pop:'Pop', jazz:'Jazz', hiphop:'Hip-Hop', classical:'Klasična', electronic:'Elektronička', reset:'↺ Resetiraj 100%', restore:'Vrati', tabsPlaying:'🔊 Kartice sa zvukom', noAudio:'Nema zvuka', madeBy:'Napravio', withLove:'s', sourceCode:'Izvorni Kod' },
  kn: { name:'Kannada — ಕನ್ನಡ', title:'HypeVox', mute:'ಮೌನ', maxVol:'1000%', default:'● ಡೀಫಾಲ್ಟ್', muted:'● ಮೌನ', soundProfile:'ಧ್ವನಿ ಪ್ರೊಫೈಲ್', off:'ಆಫ್', flat:'ಫ್ಲಾಟ್', bass:'ಬಾಸ್ ಬೂಸ್ಟ್', voice:'ಧ್ವನಿ ಸ್ಪಷ್ಟತೆ', treble:'ಟ್ರೆಬಲ್ ಬೂಸ್ಟ್', loud:'ಜೋರಾಗಿ', podcast:'ಪಾಡ್‌ಕಾಸ್ಟ್', rock:'ರಾಕ್', pop:'ಪಾಪ್', jazz:'ಜಾಝ್', hiphop:'ಹಿಪ್-ಹಾಪ್', classical:'ಕ್ಲಾಸಿಕಲ್', electronic:'ಎಲೆಕ್ಟ್ರಾನಿಕ್', reset:'↺ 100% ಮರುಹೊಂದಿಸಿ', restore:'ಮರುಸ್ಥಾಪಿಸು', tabsPlaying:'🔊 ಆಡಿಯೋ ಹೊಂದಿರುವ ಟ್ಯಾಬ್‌ಗಳು', noAudio:'ಯಾವುದೇ ಆಡಿಯೋ ಇಲ್ಲ', madeBy:'ತಯಾರಿಸಿದವರು', withLove:'ಜೊತೆ', sourceCode:'ಸೋರ್ಸ್ ಕೋಡ್' },
  lt: { name:'Lithuanian — Lietuvių', title:'HypeVox', mute:'Nutildyti', maxVol:'1000%', default:'● Numatytasis', muted:'● Nutildyta', soundProfile:'Garso Profilis', off:'Išjungta', flat:'Plokščias', bass:'Žemų Dažnių Stiprinimas', voice:'Balso Aiškumas', treble:'Aukštų Dažnių Stiprinimas', loud:'Garsumas', podcast:'Podcast', rock:'Rokas', pop:'Pop', jazz:'Džiazas', hiphop:'Hip-Hop', classical:'Klasikinė', electronic:'Elektroninė', reset:'↺ Atstatyti 100%', restore:'Atkurti', tabsPlaying:'🔊 Kortelės su garsu', noAudio:'Nėra garso', madeBy:'Sukūrė', withLove:'su', sourceCode:'Pradinis Kodas' },
  lv: { name:'Latvian — Latviešu', title:'HypeVox', mute:'Klusināt', maxVol:'1000%', default:'● Noklusējums', muted:'● Klusināts', soundProfile:'Skaņas Profils', off:'Izslēgts', flat:'Plakans', bass:'Baspastiprinājums', voice:'Balss Skaidrība', treble:'Augsto Pastiprinājums', loud:'Skaļums', podcast:'Podkāsts', rock:'Roks', pop:'Pops', jazz:'Džezs', hiphop:'Hip-Hop', classical:'Klasiskā', electronic:'Elektroniskā', reset:'↺ Atiestatīt 100%', restore:'Atjaunot', tabsPlaying:'🔊 Cilnes ar audio', noAudio:'Nav audio', madeBy:'Izveidoja', withLove:'ar', sourceCode:'Pirmkods' },
  ml: { name:'Malayalam — മലയാളം', title:'HypeVox', mute:'നിശബ്ദമാക്കുക', maxVol:'1000%', default:'● സ്ഥിരം', muted:'● നിശബ്ദം', soundProfile:'ശബ്ദ പ്രൊഫൈൽ', off:'ഓഫ്', flat:'ഫ്ലാറ്റ്', bass:'ബാസ് ബൂസ്റ്റ്', voice:'ശബ്ദ വ്യക്തത', treble:'ട്രെബിൾ ബൂസ്റ്റ്', loud:'ഉച്ചത്തിൽ', podcast:'പോഡ്കാസ്റ്റ്', rock:'റോക്ക്', pop:'പോപ്പ്', jazz:'ജാസ്', hiphop:'ഹിപ്-ഹോപ്പ്', classical:'ക്ലാസിക്കൽ', electronic:'ഇലക്ട്രോണിക്', reset:'↺ 100% പുനഃസജ്ജമാക്കുക', restore:'പുനഃസ്ഥാപിക്കുക', tabsPlaying:'🔊 ഓഡിയോ ഉള്ള ടാബുകൾ', noAudio:'ഓഡിയോ ഇല്ല', madeBy:'നിർമ്മിച്ചത്', withLove:'സ്നേഹത്തോടെ', sourceCode:'സോഴ്സ് കോഡ്' },
  mr: { name:'Marathi — मराठी', title:'HypeVox', mute:'शांत', maxVol:'1000%', default:'● डीफॉल्ट', muted:'● शांत', soundProfile:'ध्वनी प्रोफाइल', off:'बंद', flat:'सपाट', bass:'बास बूस्ट', voice:'आवाज स्पष्टता', treble:'ट्रेबल बूस्ट', loud:'मोठेपणा', podcast:'पॉडकास्ट', rock:'रॉक', pop:'पॉप', jazz:'जॅझ', hiphop:'हिप-हॉप', classical:'शास्त्रीय', electronic:'इलेक्ट्रॉनिक', reset:'↺ 100% रीसेट', restore:'पुनर्संचयित', tabsPlaying:'🔊 ऑडिओ असलेले टॅब', noAudio:'ऑडिओ नाही', madeBy:'तयार केले', withLove:'सह', sourceCode:'सोर्स कोड' },
  sk: { name:'Slovak — Slovenčina', title:'HypeVox', mute:'Stlmiť', maxVol:'1000%', default:'● Predvolené', muted:'● Stlmené', soundProfile:'Zvukový Profil', off:'Vypnuté', flat:'Plochý', bass:'Zosilnenie Basov', voice:'Čistota Hlasu', treble:'Zosilnenie Výšok', loud:'Hlasitosť', podcast:'Podcast', rock:'Rock', pop:'Pop', jazz:'Jazz', hiphop:'Hip-Hop', classical:'Klasická', electronic:'Elektronická', reset:'↺ Resetovať 100%', restore:'Obnoviť', tabsPlaying:'🔊 Karty so zvukom', noAudio:'Žiadny zvuk', madeBy:'Vytvoril', withLove:'s', sourceCode:'Zdrojový Kód' },
  sl: { name:'Slovenian — Slovenščina', title:'HypeVox', mute:'Utišaj', maxVol:'1000%', default:'● Privzeto', muted:'● Utišano', soundProfile:'Zvočni Profil', off:'Izklopljeno', flat:'Ravno', bass:'Ojačitev Basov', voice:'Jasnost Glasu', treble:'Ojačitev Visokih', loud:'Glasnost', podcast:'Podcast', rock:'Rock', pop:'Pop', jazz:'Jazz', hiphop:'Hip-Hop', classical:'Klasična', electronic:'Elektronska', reset:'↺ Ponastavi 100%', restore:'Obnovi', tabsPlaying:'🔊 Zavihki z zvokom', noAudio:'Ni zvoka', madeBy:'Naredil', withLove:'z', sourceCode:'Izvorna Koda' },
  sr: { name:'Serbian — Српски', title:'HypeVox', mute:'Утишај', maxVol:'1000%', default:'● Подразумевано', muted:'● Утишано', soundProfile:'Звучни Профил', off:'Искључено', flat:'Равно', bass:'Појачање Басова', voice:'Јасноћа Гласа', treble:'Појачање Високих', loud:'Гласноћа', podcast:'Подкаст', rock:'Рок', pop:'Поп', jazz:'Џез', hiphop:'Хип-Хоп', classical:'Класична', electronic:'Електронска', reset:'↺ Ресетуј 100%', restore:'Врати', tabsPlaying:'🔊 Картице са звуком', noAudio:'Нема звука', madeBy:'Направио', withLove:'са', sourceCode:'Изворни Код' },
  sw: { name:'Swahili — Kiswahili', title:'HypeVox', mute:'Nyamazisha', maxVol:'1000%', default:'● Chaguo-msingi', muted:'● Imenyamazishwa', soundProfile:'Wasifu wa Sauti', off:'Zima', flat:'Gorofa', bass:'Kuongeza Besi', voice:'Uwazi wa Sauti', treble:'Kuongeza Trebli', loud:'Uzito wa Sauti', podcast:'Podikasti', rock:'Roki', pop:'Pop', jazz:'Jazi', hiphop:'Hip-Hop', classical:'Klasiki', electronic:'Kielektroniki', reset:'↺ Weka Upya 100%', restore:'Rejesha', tabsPlaying:'🔊 Vichupo vyenye sauti', noAudio:'Hakuna sauti', madeBy:'Imetengenezwa na', withLove:'kwa', sourceCode:'Msimbo Chanzo' },
  te: { name:'Telugu — తెలుగు', title:'HypeVox', mute:'మౌనం', maxVol:'1000%', default:'● డిఫాల్ట్', muted:'● మౌనం', soundProfile:'ధ్వని ప్రొఫైల్', off:'ఆఫ్', flat:'ఫ్లాట్', bass:'బాస్ బూస్ట్', voice:'వాయిస్ స్పష్టత', treble:'ట్రెబుల్ బూస్ట్', loud:'బిగ్గర', podcast:'పాడ్‌కాస్ట్', rock:'రాక్', pop:'పాప్', jazz:'జాజ్', hiphop:'హిప్-హాప్', classical:'క్లాసికల్', electronic:'ఎలక్ట్రానిక్', reset:'↺ 100% రీసెట్', restore:'పునరుద్ధరించు', tabsPlaying:'🔊 ఆడియో ఉన్న ట్యాబ్‌లు', noAudio:'ఆడియో లేదు', madeBy:'తయారు చేసినవారు', withLove:'తో', sourceCode:'సోర్స్ కోడ్' },
  zh_TW: { name:'Chinese (Traditional) — 繁體中文', title:'HypeVox', mute:'靜音', maxVol:'1000%', default:'● 預設', muted:'● 靜音', soundProfile:'聲音設定', off:'關閉', flat:'平坦', bass:'低音增強', voice:'語音清晰', treble:'高音增強', loud:'響度', podcast:'播客', rock:'搖滾', pop:'流行', jazz:'爵士', hiphop:'嘻哈', classical:'古典', electronic:'電子', reset:'↺ 重設 100%', restore:'恢復', tabsPlaying:'🔊 正在播放音訊的分頁', noAudio:'無音訊', madeBy:'作者', withLove:'用', sourceCode:'原始碼' },
};

// Get current language or fallback to English
function T(key) {
  const lang = (globalThis._hvLang || 'en');
  return LANG[lang]?.[key] || LANG.en[key] || key;
}

globalThis.LANG = LANG;
globalThis.T = T;
